source 'https://rubygems.org'

gem 'brotli' # TODO remove when middleman includes by default
gem 'ffi'
gem 'middleman', github: 'middleman/middleman'
gem 'middleman-autoprefixer'
gem 'middleman-condenser', github: 'bemky/middleman-condenser', branch: 'dedup_assets'
gem 'condenser', github: 'malomalo/condenser'
gem 'css_parser'
gem 'middleman-syntax'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
gem 'rubyzip'
gem 'byebug'
gem 'uniform-ui', require: 'uniform', github: 'bemky/uniform'

# Markdown
gem 'github-markup'
gem 'commonmarker'